### ISSUE TITLE
blink(namespace)

### ISSUE THREAD

**Issue by rentalhost** [spatie/laravel-blink#2]
I don't know if it will be possible with the current implementation, but should be great if we can pass the first parameter as the namespace. For instance:

```php
blink(__CLASS__)->put('key', $value);
```

Should be equivalent to something like:

```php
blink()->push(__CLASS__ . SOME_SEPARATOR . 'key', $value);
```

The advantage that is more "clear" and we can close the scope to the current class (maybe over an object). For instance:

```php
blink($this)->put('key', $value);
```

**Comment by freekmurze** [comment]
Currently this is not possible. I'm also thinking that adding a prefix to `push` is not that bad. 

In your application you could add a method `getBlinkKey` (or something similar) that adds the prefix.

```
blink()->push($this->getBlinkKey('test'), $value);
```

**Comment by rentalhost** [comment]
Yeah, the `getBlinkKey()` is good in general, but not to SOLID, once that you give a new responsability to each class (even using traits). But we can think about a service class that do that (eg. `BlinkService::from(__CLASS__)`).

Another way to resolve that is identify if the first parameter of `blink()` is `class_exists()` or `is_object()`, then treat it in a different way. But the problem of first is that is a BC (but I really don't think that someone uses the `__CLASS__` as a key name). The problem of second is that I don't know how we can store a key based on an `object` instance, once that PHP don't supports things like that (I guess).

**Comment by freekmurze** [comment]
Another option you have is to decorate the `Blink` class. Create a new class called `NamespacedBlink` (or something similar) that accepts an instance of `Blink`. All calls from  `NamespacedBlink` should be forwarded to `Blink`. Inside `NamespacedBlink` you could add your prefix to the relevant functions.

I don't think this issue is important enough to warrant a code changes in our package.

**Comment by sebastiandedeyne** [comment]
> Yeah, the getBlinkKey() is good in general, but not to SOLID, once that you give a new responsability to each class (even using traits)

This argument doesn't really stand imo. Once you're using blink inside a class that isn't something like a decorator, strictly speaking you're breaking SRP.

I'm not saying it's bad, just that it doesn't make a difference wether the key is stored in a private method or created inline in a method call.

Lastly, regarding this issue in general, I think I'd rather keep the API in line with Laravel's session & cache API.
