### ISSUE TITLE
Question: Does it Cache Statically?

### ISSUE THREAD

**Issue by benyanke** [spatie/laravel-blink#6]
Are the caches stored statically, and shareable between instantiations of the Blink() object, or does it only live for the life of the object itself?

**Comment by freekmurze** [comment]
it only lives on the object itself

**Comment by freekmurze** [comment]
Blink is registered as a singleton, so cache is shared: https://github.com/spatie/laravel-blink/blob/master/src/BlinkServiceProvider.php#L15
